### ISSUE TITLE
Please provide some example of how to use this.

### ISSUE THREAD

**Issue by C0DK** [rebus-org/Rebus.MongoDb#10]
Seems like a great project, but the learning curve is steep.

I have a difficult time figuring out what this does and how to use it. Documentation is none-existing..

**Comment by mookid8000** [comment]
Sorry 🙂 Rebus.MongoDb provides persistence implementations for [Rebus](https://github.com/rebus-org/Rebus), and you configure it by going
```csharp
services.AddRebus(
    configure => configure
        .Transport(...)
        .Sagas(s => s.StoreInMongoDb(...)) //< 1
        .Subscriptions(s => s.StoreInMongoDb(...)) //< 2
        .Timeouts(t => t.StoreInMongoDb(...)) //< 3
);
```
using either of 1, 2, and/or 3 as you please.

Since this repository is just an integration library, you'll find much more documentation here: https://github.com/rebus-org/Rebus/wiki

**Comment by C0DK** [comment]
OIC - Could one add a link to the readme that points towards persistence in the Wiki? I cannot find the purpose. Is it just for logging, i.e.? I was thinking of using it for event sourcing, but I cannot determine if this is applicable.

**Comment by C0DK** [comment]
How can you close this issue? :D The issue hasn't gone away :P

**Comment by mookid8000** [comment]
> OIC - Could one add a link to the readme that points towards persistence in the Wiki? 



> I cannot find the purpose. Is it just for logging, i.e.? 

No, it's not for logging. Not at all. The package can be used together with [Rebus](https://github.com/rebus-org/Rebus) to make Rebus store sagas, subscriptions, and/or timeouts in MongoDB.

**Sagas** are Rebus' persistent state machines - i.e. persistent objects whose state changes are driven by messages. If you want to read more about sagas, I suggest you go to the Rebus wiki and check out the [coordinating things that happen over time](https://github.com/rebus-org/Rebus/wiki/Coordinating-stuff-that-happens-over-time) scenario.

You also might want to check out [this code sample](https://github.com/rebus-org/RebusSamples/blob/master/Sagas/README.md).

**Subscriptions** are relevant in scenarios where the queue system does not implement publish/subscribe messaging (i.e. routing via topics) natively. In those cases, Rebus can "polyfill" the pub/sub behavior by means of a subscription storage, in this case using MongoDB documents to represent topics and hold the queue names of their subscribers.

**Timeouts** are "messages sent into the future". Some queueing systems have support for putting a future timestamp on a message when it's sent, which causes the message to be delivered at a later time. Again, Rebus can polyfill this functionality by means of the timeout storage, in this case using MongoDB documents to represent messages to be delivered at a later time.


> I was thinking of using it for event sourcing, but I cannot determine if this is applicable.

It's not. 

Generally, you should not look towards queues if you want to do anything with event sourcing, because queues are terrible at delivering messages in order, and the order of events is almost always pretty important.
